### ISSUE TITLE
Unable to access WebDAV

### ISSUE THREAD

**Issue by carlyman** [ChatDeBlofeld/seafile-arm-docker#3]
Does this ARM image support WebDAV?

I have a previous x64 version of the official Seafile that I'm able to access via Webdav, but am moving to an ARM-based server. I've updated my nginx reverse-proxy and updated seafdav.conf (see below)
```
[WEBDAV]
enabled = true
host = seafile
port = 8080
fastcgi = false
share_name = /seafdav
```
``` nginx
location /seafdav {
        proxy_pass         http://seafile:8080/seafdav;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Host $server_name;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_read_timeout  1200s;
        client_max_body_size 0;
}
```

But I am unable to connect.  Trying to understand if this image supports WebDAV.  In the seafile docker logs, I don't see any mention of WebDAV or port 8080.  Thanks.

**Comment by ChatDeBlofeld** [comment]
Hi,

Although the focus of this image isn't to have WebDAV working (it could therefore break in the future, this had to be said), it **should** allow to use it with little effort.

Then, in this case, some dependencies were missing (look at the `controller.log` file in the `logs` directory) due to a broken link in the build script I rely on.

I fixed that and I'm currently rebuilding the images (they should be available soon), let me know if that solved your problem.

**Comment by carlyman** [comment]
Perfect, that fixed it.  I tried adding some dependencies, but couldn't figure them all out.  And understood that WebDAV may break in the future.  Thanks!
