### ISSUE TITLE
Failed to start seafile server

### ISSUE THREAD

**Issue by vicat47** [ChatDeBlofeld/seafile-arm-docker#4]
Respberry 4B start service failed

When I run the `docker-compose up`, I got the logs blow
```
seafile_1  | Error: there is no ccnet config directory.
seafile_1  | Have you run setup-seafile.sh before this?
```
so i tried to create directory named `ccnet` in `./seafile/ccnet` and volume to container `./seafile/ccnet:/shared/ccnet`

but get new error blow,,
```
seafile_1  | Starting seafile server, please wait ...
seafile_1  | ** Message: 05:52:14.153: seafile-controller.c(535): No seafevents.
seafile_1  |
seafile_1  | Failed to start seafile server
seafile_1  |
seafile_1  | LANG is not set in ENV, set to en_US.UTF-8
seafile_1  | LC_ALL is not set in ENV, set to en_US.UTF-8
seafile_1  | ./seafile-server-latest/seahub.sh: line 210: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
seafile_1  |
seafile_1  | Warning: seafile-controller not running. Have you run "./seafile.sh start" ?
```

Database is running successful, but seafile service can't start, what should I do
Do I need `docker exec` to run `./seafile.sh start` ?

thanks

**Comment by ChatDeBlofeld** [comment]
Hi,

It looks like you're not using the latest image version. Try to update with `docker-compose pull`

If this is intentional, well, I only support the latest version. The older tags are kept on the hub "just in case" but aren't intended to be used to set up a new instance (should document this somewhere...). 

Still, I you really want/need to use an older image, you can checkout to an older commit. For example a8f76923ac83589491300360449cf0ad99725f3a should be fine for 7.1.9/8.0.2

**Comment by vicat47** [comment]
Thanks
I'll use the latest version
